language: scala
jdk:
        - oraclejdk8
before_script:
        - npm install
        - psql -c "create database revveries-test;" -U postgres
script:
        - ./sbt -DJDBC_TEST_URI="jdbc:postgresql:revveries-test" -DJDBC_TEST_BASE_URL="jdbc:postgresql:revveries-test" -DJDBC_TEST_USER="postgres" -DJDBC_TEST_PASSWORD='' test
        - gulp spec
