 development:
   host: dev.example.com
   email: <%= ENV['LOCOMOTIVE_EMAIL'] %>
   password: <%= ENV['LOCOMOTIVE_PASSWORD'] %>
   api_key: <%= ENV['LOCOMOTIVE_API_KEY'] %>
 staging:
   host: staging.example.com
   email: <%= ENV['LOCOMOTIVE_EMAIL'] %>
   password: <%= ENV['LOCOMOTIVE_PASSWORD'] %>
   api_key: <%= ENV['LOCOMOTIVE_API_KEY'] %>
 production:
   host: <%= ENV['HOST_NAME'] %>
   email: <%= ENV['LOCOMOTIVE_EMAIL'] %>
   password: <%= ENV['LOCOMOTIVE_PASSWORD'] %>
   api_key: <%= ENV['LOCOMOTIVE_API_KEY'] %>
